name: Metrics

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Stats card
        uses: readme-tools/github-readme-stats-action@b4d2ef3b8051484b318d455163153b23a2b35fa2 # v1.1.0
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=transparent&show=reviews,prs_merged,prs_merged_percentage&include_all_commits=true&custom_title=GitHub%20Stats&hide_border=true
          path: cards/stats.svg
          token: ${{ secrets.METRICS_TOKEN }}

      - name: WakaTime card
        uses: readme-tools/github-readme-stats-action@b4d2ef3b8051484b318d455163153b23a2b35fa2 # v1.1.0
        with:
          card: wakatime
          options: username=guicaulada&layout=compact&theme=transparent&hide_border=true&langs_count=50&api_key=${{ secrets.WAKATIME_API_KEY }}
          path: cards/wakatime.svg
          token: ${{ secrets.METRICS_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add cards/*.svg
          git commit -m "chore: update readme stats cards" || exit 0
          git push
